layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name:  The Rust Programming Language 
    web_url: https://github.com/rust-lang/
    image_url: https://avatars3.githubusercontent.com/u/5430905?s=200&v=4

  - name: WebAssembly
    web_url: https://github.com/WebAssembly
    image_url: https://avatars1.githubusercontent.com/u/11578470?s=200&v=4
